name: app3_ciencia_dados
description: "NutriHealth Analytics - Monitoramento Nutricional com IA"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Gráficos interativos
  fl_chart: ^0.69.0
  
  # Exportação CSV
  csv: ^6.0.0
  
  # Exportação HTML/PDF para web
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
